package BackEnd;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ruri
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pegawai = new javax.swing.JButton();
        pembeli = new javax.swing.JButton();
        produk = new javax.swing.JButton();
        alamatpembeli = new javax.swing.JButton();
        produktiappesanan = new javax.swing.JButton();
        keranjangbelanja = new javax.swing.JButton();
        pengiriman = new javax.swing.JButton();
        pesanan = new javax.swing.JButton();
        pembayaran = new javax.swing.JButton();
        nomortelepon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("BERANDA BACK END");

        pegawai.setText("Pegawai");
        pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegawaiActionPerformed(evt);
            }
        });

        pembeli.setText("Pembeli");
        pembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembeliActionPerformed(evt);
            }
        });

        produk.setText("Produk");
        produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkActionPerformed(evt);
            }
        });

        alamatpembeli.setText("Alamat Pembeli");
        alamatpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatpembeliActionPerformed(evt);
            }
        });

        produktiappesanan.setText("Produk Setiap Pesanan");

        keranjangbelanja.setText("Keranjang Belanja");
        keranjangbelanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keranjangbelanjaActionPerformed(evt);
            }
        });

        pengiriman.setText("Pengiriman");
        pengiriman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengirimanActionPerformed(evt);
            }
        });

        pesanan.setText("Pesanan");
        pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesananActionPerformed(evt);
            }
        });

        pembayaran.setText("Pembayaran");
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });

        nomortelepon.setText("Nomor Telepon");
        nomortelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorteleponActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pengiriman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(produktiappesanan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(produk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pembeli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomortelepon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alamatpembeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keranjangbelanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pegawai)
                        .addGap(18, 18, 18)
                        .addComponent(alamatpembeli)
                        .addGap(18, 18, 18)
                        .addComponent(keranjangbelanja)
                        .addGap(18, 18, 18)
                        .addComponent(pesanan)
                        .addGap(18, 18, 18)
                        .addComponent(nomortelepon))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pembeli)
                        .addGap(18, 18, 18)
                        .addComponent(produk)
                        .addGap(18, 18, 18)
                        .addComponent(produktiappesanan)
                        .addGap(18, 18, 18)
                        .addComponent(pengiriman)
                        .addGap(18, 18, 18)
                        .addComponent(pembayaran)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegawaiActionPerformed
        FormPegawai field = new FormPegawai();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pegawaiActionPerformed

    private void produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkActionPerformed
        // TODO add your handling code here:
        Produk field = new Produk();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_produkActionPerformed

    private void pengirimanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengirimanActionPerformed
        // TODO add your handling code here:
        Pengiriman field = new Pengiriman();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pengirimanActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
        Pembayaran field = new Pembayaran();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pembayaranActionPerformed

    private void alamatpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatpembeliActionPerformed
        // TODO add your handling code here:
        AlamatPembeli field = new AlamatPembeli();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_alamatpembeliActionPerformed

    private void keranjangbelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keranjangbelanjaActionPerformed
        // TODO add your handling code here:
        KeranjangBelanja field = new KeranjangBelanja();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_keranjangbelanjaActionPerformed

    private void pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesananActionPerformed
        // TODO add your handling code here:
        Pesanan field = new Pesanan();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pesananActionPerformed

    private void nomorteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorteleponActionPerformed
        // TODO add your handling code here:
        NoTelp field = new NoTelp();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_nomorteleponActionPerformed

    private void pembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembeliActionPerformed
        // TODO add your handling code here:
        Pembeli field = new Pembeli();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pembeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alamatpembeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton keranjangbelanja;
    private javax.swing.JButton nomortelepon;
    private javax.swing.JButton pegawai;
    private javax.swing.JButton pembayaran;
    private javax.swing.JButton pembeli;
    private javax.swing.JButton pengiriman;
    private javax.swing.JButton pesanan;
    private javax.swing.JButton produk;
    private javax.swing.JButton produktiappesanan;
    // End of variables declaration//GEN-END:variables
}
